class_name Enums

enum SkillTypes { 
	CANNON_COOLDOWN, HULL_PLATING, SHIELDS_ENABLED, SHIELD_MAX_ENERGY, SHIELD_DRAIN_RATE, SHIELD_CHARGE_RATE, SHIELD_TIMEOUT,
	BUCKS_CONVERSION_RATE, POINTS_MULTIPLIER, NUM_SMART_BOMBS,
	RESPEC_ENABLED, TOP_SHIELD_BOUNCE, RIGHT_SHIELD_BOUNCE,
	BOTTOM_SHIELD_BOUNCE, LEFT_SHIELD_BOUNCE, AUTOFIRE_TOP,
	AUTOFIRE_RIGHT, AUTOFIRE_BOTTOM, AUTOFIRE_LEFT, MULTISHIELD_ENABLED,
	AUTOSHIELD_TOP, AUTOSHIELD_RIGHT, AUTOSHIELD_BOTTOM, AUTOSHIELD_LEFT,
	QTC_CHARGE_TIME, QTC_ORBIT_SPEED, QTC_CHAIN_LENGTH
}

enum SkillModifierTypes { ADD, MULTIPLY, ENABLE }
