class_name Enums

enum SkillTypes { 
	CANNON_COOLDOWN, HULL_PLATING, SHIELDS_ENABLED, SHIELD_MAX_ENERGY, SHIELD_DRAIN_RATE, SHIELD_CHARGE_RATE, SHIELD_TIMEOUT,
	BUCKS_CONVERSION_RATE, POINTS_MULTIPLIER, NUM_SMART_BOMBS,
	RESPEC_ENABLED, TOP_SHIELD_BOUNCE_ENABLED, RIGHT_SHIELD_BOUNCE_ENABLED,
	BOTTOM_SHIELD_BOUNCE_ENABLED, LEFT_SHIELD_BOUNCE_ENABLED, AUTOFIRE_TOP_ENABLED,
	AUTOFIRE_RIGHT_ENABLED, AUTOFIRE_BOTTOM_ENABLED, AUTOFIRE_LEFT_ENABLED, MULTISHIELD_ENABLED,
	AUTOSHIELD_TOP_ENABLED, AUTOSHIELD_RIGHT_ENABLED, AUTOSHIELD_BOTTOM_ENABLED, AUTOSHIELD_LEFT_ENABLED,
	QTC_CHARGE_TIME, QTC_ORBIT_SPEED, QTC_CHAIN_LENGTH
}

enum SkillModifierTypes { ADD, MULTIPLY, ENABLE }
